# Generated by Django 6.0.7 on 2026-07-11 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uyga vazifa',
                'verbose_name_plural': 'Uyga vazifalar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Kimtomonidan yaratilgan')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.course', verbose_name='Kurs')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'super_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name="Biriktirilgan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'unique_together': {('name', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ControlExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif / savollar matni')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='control_exams/', verbose_name='Fayl (ixtiyoriy)')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='Kim joylagan')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_exams', to='core.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Nazorat ishi',
                'verbose_name_plural': 'Nazorat ishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.homework', verbose_name='Uyga vazifa')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, verbose_name='Video havolasi (YouTube va h.k.)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lesson_videos/', verbose_name='Video fayl (ixtiyoriy)')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_part', to='core.homework', verbose_name='Uyga vazifa')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars mavzusi')),
                ('lecture_text', models.TextField(verbose_name='Maruza matni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_lessons', to='core.course', verbose_name='Kurs (Open Access uchun)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name="Kim qo'shgan")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='core.lesson', verbose_name='Dars'),
        ),
        migrations.CreateModel(
            name='OpenAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_access_students', to='core.course', verbose_name='Kurs')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'open_access'}, on_delete=django.db.models.deletion.CASCADE, related_name='open_access_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Open Access profili',
                'verbose_name_plural': 'Open Access profillari',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=255, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=255, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=255, verbose_name='D variant')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.homework', verbose_name='Uyga vazifa')),
            ],
            options={
                'verbose_name': 'Quiz savoli',
                'verbose_name_plural': 'Quiz savollari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('first', '1-tugma'), ('second', '2-tugma')], max_length=10, unique=True, verbose_name="O'rni")),
                ('button_label', models.CharField(default='Batafsil', max_length=40, verbose_name='Tugma matni')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('icon_image', models.ImageField(blank=True, help_text="Yuklansa, tugmada standart belgi o'rniga shu rasm ko'rinadi.", null=True, upload_to='showcase_icons/', verbose_name='Tugma rasmi (ixtiyoriy)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_showcase_cards', to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yangilangan')),
            ],
            options={
                'verbose_name': "Ko'rsatma tugmasi",
                'verbose_name_plural': "Ko'rsatma tugmalari",
                'ordering': ('slot',),
            },
        ),
        migrations.CreateModel(
            name='TaskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rtacha"), ('hard', 'Qiyin')], max_length=10, verbose_name='Daraja')),
                ('instructions', models.TextField(verbose_name='Topshiriq matni')),
                ('access_code', models.CharField(max_length=50, verbose_name='Kirish kodi')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_levels', to='core.homework', verbose_name='Uyga vazifa')),
            ],
            options={
                'verbose_name': 'Topshiriq darajasi',
                'verbose_name_plural': 'Topshiriq darajalari',
                'ordering': ['level'],
                'unique_together': {('homework', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ControlExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='control_exam_answers/', verbose_name='Talaba javobi (fayl)')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ball')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholangan vaqt')),
                ('ai_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='AI taklif qilgan ball')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='AI tekshirgan vaqt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.controlexam', verbose_name='Nazorat ishi')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_exam_scores', to=settings.AUTH_USER_MODEL, verbose_name='Kim baholadi')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='control_exam_scores', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Nazorat ishi bahosi',
                'verbose_name_plural': 'Nazorat ishi baholari',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Guruhda faolmi')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Guruhdan chiqarilgan vaqt')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Kim biriktirgan (Admin)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Guruh a'zoligi",
                'verbose_name_plural': "Guruh a'zoliklari",
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='3-qism ball (0-10)')),
                ('activity_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Faollik ball (0-10)')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI izohi (Open Access uchun)')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_homework_grades', to=settings.AUTH_USER_MODEL, verbose_name='Kim baholadi')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.homework', verbose_name='Uyga vazifa')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='homework_grades', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Uyga vazifa bahosi',
                'verbose_name_plural': 'Uyga vazifa baholari',
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ObserverConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now=True, verbose_name='Tanishib chiqqan vaqti')),
                ('observer', models.ForeignKey(limit_choices_to={'role': 'observer'}, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations_made', to=settings.AUTH_USER_MODEL, verbose_name='Kuzatuvchi')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='observer_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Tanishib chiqish belgisi',
                'verbose_name_plural': 'Tanishib chiqish belgilari',
                'unique_together': {('observer', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Javob matni')),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.homeworkquestion', verbose_name='Savol')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Savolga javob',
                'verbose_name_plural': 'Savollarga javoblar',
                'unique_together': {('question', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to=settings.AUTH_USER_MODEL)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='core.quizquestion')),
            ],
            options={
                'unique_together': {('quiz_question', 'student')},
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0, verbose_name='Ball (15 balldan)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='core.homework', verbose_name='Uyga vazifa')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Quiz natijasi',
                'verbose_name_plural': 'Quiz natijalari',
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Kod bilan ochilgan vaqt')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='task_answers/', verbose_name='Javob fayli')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuklangan vaqt')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ball')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('ai_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='AI taklif qilgan ball')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='AI tekshirgan vaqt')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Kim baholadi')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('task_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.tasklevel', verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Topshiriq javobi',
                'verbose_name_plural': 'Topshiriq javoblari',
                'unique_together': {('task_level', 'student')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='Talaba')),
                ('video_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.homeworkvideo', verbose_name='Video')),
            ],
            options={
                'verbose_name': "Video ko'rish belgisi",
                'verbose_name_plural': "Video ko'rish belgilari",
                'unique_together': {('video_part', 'student')},
            },
        ),
    ]
