# Generated by Django 6.0.7 on 2026-07-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lecture_file',
            field=models.FileField(blank=True, help_text="PDF, Word, PowerPoint yoki boshqa fayl — matn o'rniga yoki qo'shimcha sifatida yuklashingiz mumkin.", null=True, upload_to='lecture_files/', verbose_name='Maruza fayli (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lecture_text',
            field=models.TextField(blank=True, verbose_name='Maruza matni'),
        ),
    ]
