# Generated by Django 6.0.7 on 2026-07-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lesson_lecture_file_alter_lesson_lecture_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasecard',
            name='slot',
            field=models.CharField(choices=[('first', '1-tugma'), ('second', '2-tugma'), ('third', '3-tugma'), ('fourth', '4-tugma')], max_length=10, unique=True, verbose_name="O'rni"),
        ),
    ]
