# Generated by Django 6.0.7 on 2026-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_showcasecard_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecard',
            name='word_file',
            field=models.FileField(blank=True, help_text="Word (.docx) fayl yuklasangiz, undagi matn avtomatik ajratib olinib, yuqoridagi 'Matn' maydoniga (saytning o'z rangida) joylanadi.", null=True, upload_to='showcase_docs/', verbose_name='Word fayldan matn olish (ixtiyoriy)'),
        ),
    ]
