# Generated by Django 6.0.7 on 2026-07-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_showcasecard_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasecard',
            name='content_html',
            field=models.TextField(blank=True, help_text="Word fayl yuklanganda avtomatik to'ldiriladi — matn, sarlavha va rasmlarni o'z joyida saqlaydi, faqat sayt ranglarida ko'rsatiladi.", verbose_name='Word fayldan olingan HTML (rasmlar bilan)'),
        ),
    ]
